/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVotingRouteImport } from './routes/_authenticated/voting'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPortfolioRouteImport } from './routes/_authenticated/portfolio'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedDealsRouteImport } from './routes/_authenticated/deals'
import { Route as AuthenticatedAnnouncementsRouteImport } from './routes/_authenticated/announcements'
import { Route as AuthenticatedAllocationsRouteImport } from './routes/_authenticated/allocations'
import { Route as AuthenticatedManagerIndexRouteImport } from './routes/_authenticated/manager.index'
import { Route as AuthenticatedManagerSettingsRouteImport } from './routes/_authenticated/manager.settings'
import { Route as AuthenticatedManagerPortfolioRouteImport } from './routes/_authenticated/manager.portfolio'
import { Route as AuthenticatedManagerPollsRouteImport } from './routes/_authenticated/manager.polls'
import { Route as AuthenticatedManagerPaymentsRouteImport } from './routes/_authenticated/manager.payments'
import { Route as AuthenticatedManagerMembersRouteImport } from './routes/_authenticated/manager.members'
import { Route as AuthenticatedManagerLeadershipRouteImport } from './routes/_authenticated/manager.leadership'
import { Route as AuthenticatedManagerDocumentsRouteImport } from './routes/_authenticated/manager.documents'
import { Route as AuthenticatedManagerDealsRouteImport } from './routes/_authenticated/manager.deals'
import { Route as AuthenticatedManagerApplicationsRouteImport } from './routes/_authenticated/manager.applications'
import { Route as AuthenticatedManagerAnnouncementsRouteImport } from './routes/_authenticated/manager.announcements'
import { Route as AuthenticatedManagerAllocationsRouteImport } from './routes/_authenticated/manager.allocations'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVotingRoute = AuthenticatedVotingRouteImport.update({
  id: '/voting',
  path: '/voting',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortfolioRoute = AuthenticatedPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDealsRoute = AuthenticatedDealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnnouncementsRoute =
  AuthenticatedAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAllocationsRoute =
  AuthenticatedAllocationsRouteImport.update({
    id: '/allocations',
    path: '/allocations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerIndexRoute =
  AuthenticatedManagerIndexRouteImport.update({
    id: '/manager/',
    path: '/manager/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerSettingsRoute =
  AuthenticatedManagerSettingsRouteImport.update({
    id: '/manager/settings',
    path: '/manager/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerPortfolioRoute =
  AuthenticatedManagerPortfolioRouteImport.update({
    id: '/manager/portfolio',
    path: '/manager/portfolio',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerPollsRoute =
  AuthenticatedManagerPollsRouteImport.update({
    id: '/manager/polls',
    path: '/manager/polls',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerPaymentsRoute =
  AuthenticatedManagerPaymentsRouteImport.update({
    id: '/manager/payments',
    path: '/manager/payments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerMembersRoute =
  AuthenticatedManagerMembersRouteImport.update({
    id: '/manager/members',
    path: '/manager/members',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerLeadershipRoute =
  AuthenticatedManagerLeadershipRouteImport.update({
    id: '/manager/leadership',
    path: '/manager/leadership',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerDocumentsRoute =
  AuthenticatedManagerDocumentsRouteImport.update({
    id: '/manager/documents',
    path: '/manager/documents',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerDealsRoute =
  AuthenticatedManagerDealsRouteImport.update({
    id: '/manager/deals',
    path: '/manager/deals',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerApplicationsRoute =
  AuthenticatedManagerApplicationsRouteImport.update({
    id: '/manager/applications',
    path: '/manager/applications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerAnnouncementsRoute =
  AuthenticatedManagerAnnouncementsRouteImport.update({
    id: '/manager/announcements',
    path: '/manager/announcements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerAllocationsRoute =
  AuthenticatedManagerAllocationsRouteImport.update({
    id: '/manager/allocations',
    path: '/manager/allocations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/allocations': typeof AuthenticatedAllocationsRoute
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/deals': typeof AuthenticatedDealsRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/portfolio': typeof AuthenticatedPortfolioRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/voting': typeof AuthenticatedVotingRoute
  '/manager/allocations': typeof AuthenticatedManagerAllocationsRoute
  '/manager/announcements': typeof AuthenticatedManagerAnnouncementsRoute
  '/manager/applications': typeof AuthenticatedManagerApplicationsRoute
  '/manager/deals': typeof AuthenticatedManagerDealsRoute
  '/manager/documents': typeof AuthenticatedManagerDocumentsRoute
  '/manager/leadership': typeof AuthenticatedManagerLeadershipRoute
  '/manager/members': typeof AuthenticatedManagerMembersRoute
  '/manager/payments': typeof AuthenticatedManagerPaymentsRoute
  '/manager/polls': typeof AuthenticatedManagerPollsRoute
  '/manager/portfolio': typeof AuthenticatedManagerPortfolioRoute
  '/manager/settings': typeof AuthenticatedManagerSettingsRoute
  '/manager/': typeof AuthenticatedManagerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/allocations': typeof AuthenticatedAllocationsRoute
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/deals': typeof AuthenticatedDealsRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/portfolio': typeof AuthenticatedPortfolioRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/voting': typeof AuthenticatedVotingRoute
  '/manager/allocations': typeof AuthenticatedManagerAllocationsRoute
  '/manager/announcements': typeof AuthenticatedManagerAnnouncementsRoute
  '/manager/applications': typeof AuthenticatedManagerApplicationsRoute
  '/manager/deals': typeof AuthenticatedManagerDealsRoute
  '/manager/documents': typeof AuthenticatedManagerDocumentsRoute
  '/manager/leadership': typeof AuthenticatedManagerLeadershipRoute
  '/manager/members': typeof AuthenticatedManagerMembersRoute
  '/manager/payments': typeof AuthenticatedManagerPaymentsRoute
  '/manager/polls': typeof AuthenticatedManagerPollsRoute
  '/manager/portfolio': typeof AuthenticatedManagerPortfolioRoute
  '/manager/settings': typeof AuthenticatedManagerSettingsRoute
  '/manager': typeof AuthenticatedManagerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/allocations': typeof AuthenticatedAllocationsRoute
  '/_authenticated/announcements': typeof AuthenticatedAnnouncementsRoute
  '/_authenticated/deals': typeof AuthenticatedDealsRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/portal': typeof AuthenticatedPortalRoute
  '/_authenticated/portfolio': typeof AuthenticatedPortfolioRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/voting': typeof AuthenticatedVotingRoute
  '/_authenticated/manager/allocations': typeof AuthenticatedManagerAllocationsRoute
  '/_authenticated/manager/announcements': typeof AuthenticatedManagerAnnouncementsRoute
  '/_authenticated/manager/applications': typeof AuthenticatedManagerApplicationsRoute
  '/_authenticated/manager/deals': typeof AuthenticatedManagerDealsRoute
  '/_authenticated/manager/documents': typeof AuthenticatedManagerDocumentsRoute
  '/_authenticated/manager/leadership': typeof AuthenticatedManagerLeadershipRoute
  '/_authenticated/manager/members': typeof AuthenticatedManagerMembersRoute
  '/_authenticated/manager/payments': typeof AuthenticatedManagerPaymentsRoute
  '/_authenticated/manager/polls': typeof AuthenticatedManagerPollsRoute
  '/_authenticated/manager/portfolio': typeof AuthenticatedManagerPortfolioRoute
  '/_authenticated/manager/settings': typeof AuthenticatedManagerSettingsRoute
  '/_authenticated/manager/': typeof AuthenticatedManagerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/allocations'
    | '/announcements'
    | '/deals'
    | '/documents'
    | '/payments'
    | '/portal'
    | '/portfolio'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/voting'
    | '/manager/allocations'
    | '/manager/announcements'
    | '/manager/applications'
    | '/manager/deals'
    | '/manager/documents'
    | '/manager/leadership'
    | '/manager/members'
    | '/manager/payments'
    | '/manager/polls'
    | '/manager/portfolio'
    | '/manager/settings'
    | '/manager/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/allocations'
    | '/announcements'
    | '/deals'
    | '/documents'
    | '/payments'
    | '/portal'
    | '/portfolio'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/voting'
    | '/manager/allocations'
    | '/manager/announcements'
    | '/manager/applications'
    | '/manager/deals'
    | '/manager/documents'
    | '/manager/leadership'
    | '/manager/members'
    | '/manager/payments'
    | '/manager/polls'
    | '/manager/portfolio'
    | '/manager/settings'
    | '/manager'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/allocations'
    | '/_authenticated/announcements'
    | '/_authenticated/deals'
    | '/_authenticated/documents'
    | '/_authenticated/payments'
    | '/_authenticated/portal'
    | '/_authenticated/portfolio'
    | '/_authenticated/profile'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/voting'
    | '/_authenticated/manager/allocations'
    | '/_authenticated/manager/announcements'
    | '/_authenticated/manager/applications'
    | '/_authenticated/manager/deals'
    | '/_authenticated/manager/documents'
    | '/_authenticated/manager/leadership'
    | '/_authenticated/manager/members'
    | '/_authenticated/manager/payments'
    | '/_authenticated/manager/polls'
    | '/_authenticated/manager/portfolio'
    | '/_authenticated/manager/settings'
    | '/_authenticated/manager/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/voting': {
      id: '/_authenticated/voting'
      path: '/voting'
      fullPath: '/voting'
      preLoaderRoute: typeof AuthenticatedVotingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portfolio': {
      id: '/_authenticated/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof AuthenticatedPortfolioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deals': {
      id: '/_authenticated/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof AuthenticatedDealsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/announcements': {
      id: '/_authenticated/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AuthenticatedAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/allocations': {
      id: '/_authenticated/allocations'
      path: '/allocations'
      fullPath: '/allocations'
      preLoaderRoute: typeof AuthenticatedAllocationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/': {
      id: '/_authenticated/manager/'
      path: '/manager'
      fullPath: '/manager/'
      preLoaderRoute: typeof AuthenticatedManagerIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/settings': {
      id: '/_authenticated/manager/settings'
      path: '/manager/settings'
      fullPath: '/manager/settings'
      preLoaderRoute: typeof AuthenticatedManagerSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/portfolio': {
      id: '/_authenticated/manager/portfolio'
      path: '/manager/portfolio'
      fullPath: '/manager/portfolio'
      preLoaderRoute: typeof AuthenticatedManagerPortfolioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/polls': {
      id: '/_authenticated/manager/polls'
      path: '/manager/polls'
      fullPath: '/manager/polls'
      preLoaderRoute: typeof AuthenticatedManagerPollsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/payments': {
      id: '/_authenticated/manager/payments'
      path: '/manager/payments'
      fullPath: '/manager/payments'
      preLoaderRoute: typeof AuthenticatedManagerPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/members': {
      id: '/_authenticated/manager/members'
      path: '/manager/members'
      fullPath: '/manager/members'
      preLoaderRoute: typeof AuthenticatedManagerMembersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/leadership': {
      id: '/_authenticated/manager/leadership'
      path: '/manager/leadership'
      fullPath: '/manager/leadership'
      preLoaderRoute: typeof AuthenticatedManagerLeadershipRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/documents': {
      id: '/_authenticated/manager/documents'
      path: '/manager/documents'
      fullPath: '/manager/documents'
      preLoaderRoute: typeof AuthenticatedManagerDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/deals': {
      id: '/_authenticated/manager/deals'
      path: '/manager/deals'
      fullPath: '/manager/deals'
      preLoaderRoute: typeof AuthenticatedManagerDealsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/applications': {
      id: '/_authenticated/manager/applications'
      path: '/manager/applications'
      fullPath: '/manager/applications'
      preLoaderRoute: typeof AuthenticatedManagerApplicationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/announcements': {
      id: '/_authenticated/manager/announcements'
      path: '/manager/announcements'
      fullPath: '/manager/announcements'
      preLoaderRoute: typeof AuthenticatedManagerAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/allocations': {
      id: '/_authenticated/manager/allocations'
      path: '/manager/allocations'
      fullPath: '/manager/allocations'
      preLoaderRoute: typeof AuthenticatedManagerAllocationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAllocationsRoute: typeof AuthenticatedAllocationsRoute
  AuthenticatedAnnouncementsRoute: typeof AuthenticatedAnnouncementsRoute
  AuthenticatedDealsRoute: typeof AuthenticatedDealsRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRoute
  AuthenticatedPortfolioRoute: typeof AuthenticatedPortfolioRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedVotingRoute: typeof AuthenticatedVotingRoute
  AuthenticatedManagerAllocationsRoute: typeof AuthenticatedManagerAllocationsRoute
  AuthenticatedManagerAnnouncementsRoute: typeof AuthenticatedManagerAnnouncementsRoute
  AuthenticatedManagerApplicationsRoute: typeof AuthenticatedManagerApplicationsRoute
  AuthenticatedManagerDealsRoute: typeof AuthenticatedManagerDealsRoute
  AuthenticatedManagerDocumentsRoute: typeof AuthenticatedManagerDocumentsRoute
  AuthenticatedManagerLeadershipRoute: typeof AuthenticatedManagerLeadershipRoute
  AuthenticatedManagerMembersRoute: typeof AuthenticatedManagerMembersRoute
  AuthenticatedManagerPaymentsRoute: typeof AuthenticatedManagerPaymentsRoute
  AuthenticatedManagerPollsRoute: typeof AuthenticatedManagerPollsRoute
  AuthenticatedManagerPortfolioRoute: typeof AuthenticatedManagerPortfolioRoute
  AuthenticatedManagerSettingsRoute: typeof AuthenticatedManagerSettingsRoute
  AuthenticatedManagerIndexRoute: typeof AuthenticatedManagerIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAllocationsRoute: AuthenticatedAllocationsRoute,
  AuthenticatedAnnouncementsRoute: AuthenticatedAnnouncementsRoute,
  AuthenticatedDealsRoute: AuthenticatedDealsRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedPortalRoute: AuthenticatedPortalRoute,
  AuthenticatedPortfolioRoute: AuthenticatedPortfolioRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedVotingRoute: AuthenticatedVotingRoute,
  AuthenticatedManagerAllocationsRoute: AuthenticatedManagerAllocationsRoute,
  AuthenticatedManagerAnnouncementsRoute:
    AuthenticatedManagerAnnouncementsRoute,
  AuthenticatedManagerApplicationsRoute: AuthenticatedManagerApplicationsRoute,
  AuthenticatedManagerDealsRoute: AuthenticatedManagerDealsRoute,
  AuthenticatedManagerDocumentsRoute: AuthenticatedManagerDocumentsRoute,
  AuthenticatedManagerLeadershipRoute: AuthenticatedManagerLeadershipRoute,
  AuthenticatedManagerMembersRoute: AuthenticatedManagerMembersRoute,
  AuthenticatedManagerPaymentsRoute: AuthenticatedManagerPaymentsRoute,
  AuthenticatedManagerPollsRoute: AuthenticatedManagerPollsRoute,
  AuthenticatedManagerPortfolioRoute: AuthenticatedManagerPortfolioRoute,
  AuthenticatedManagerSettingsRoute: AuthenticatedManagerSettingsRoute,
  AuthenticatedManagerIndexRoute: AuthenticatedManagerIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
